'use client';

import React from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardActions, Button, Typography, Grid, Box } from '@mui/material';
import { IconFileDescription } from '@tabler/icons-react';

const reportTools = [
  {
    name: 'Snyk',
    provider: 'snyk',
    logo: '/images/logos/snyk-logo.png', // Make sure these paths are correct
    description: 'View all Snyk-generated vulnerability reports and findings.'
  },
  {
    name: 'Semgrep',
    provider: 'semgrep',
    logo: '/images/logos/semgrep.png',
    description: 'Browse static analysis results from Semgrep reports.'
  },
  {
    name: 'Dhanush',
    provider: 'dhanush',
    logo: '/images/logos/dhanushsmall.png',
    description: 'Explore custom security tool reports generated by Dhanush.'
  },
  {
    name: 'Nessus',
    provider: 'nessus',
    logo: '/images/logos/nessus.png',
    description: 'Review vulnerability scan data from Nessus scans.'
  },
  {
    name: 'Nmap',
    provider: 'nmap',
    logo: '/images/logos/nmap.jpeg',
    description: 'Check port scanning reports and service discovery via Nmap.'
  },
  {
    name: 'VAPT',
    provider: 'vapt',
    logo: '/images/logos/vapt.png',
    description: 'Access full penetration testing reports and attack vectors.'
  },
];

const ReportsCard = () => {
  const router = useRouter();

  const handleViewReport = (provider) => {
    router.push(`/dashboard/secure-code-review/reports/${provider}`);

  };

  return (
    <Grid container spacing={3} >
      {reportTools.map((tool, index) => (
        <Grid item xs={12} sm={6} md={4} key={index}>
          <Card variant="outlined" sx={{ height: '100%' }}>
            <CardContent>
              <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                <Box
                  sx={{
                    width: 40,
                    height: 40,
                    p: 0.5,
                    borderRadius: 1,
                    border: '1px solid #ccc',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    mr: 1.5,
                    backgroundColor: '#f9f9f9',
                  }}
                >
                  <Image
                    src={tool.logo}
                    alt={`${tool.name} logo`}
                    width={24}
                    height={24}
                    style={{ objectFit: 'contain' }}
                  />
                </Box>
                <Typography variant="h6">{tool.name}</Typography>
              </Box>
              <Typography variant="body2" color="text.secondary">
                {tool.description}
              </Typography>
            </CardContent>
            <CardActions>
              <Button
                variant="contained"
                startIcon={<IconFileDescription />}
                onClick={() => handleViewReport(tool.provider)}
                sx={{
                  backgroundColor: '#1976d2',
                  color: '#ffffff',
                  '& .MuiButton-startIcon': {
                    color: '#ff784e',
                  },
                  '&:hover': {
                    backgroundColor: '#ff784e',
                    color: '#ffffff',
                    '& .MuiButton-startIcon': {
                      color: '#1976d2',
                    },
                  },
                }}
              >
                View Report
              </Button>
            </CardActions>
          </Card>
        </Grid>
      ))}
    </Grid>
  );
};

export default ReportsCard;
